package main

import (
	"fmt"
	"log"

	"github.com/coregx/gxpdf/creator"
)

func main() {
	// Create a new PDF creator
	c := creator.New()
	c.SetTitle("Text Rendering Example")
	c.SetAuthor("GxPDF")
	c.SetSubject("Demonstration of text rendering capabilities")

	// Create a new page
	page, err := c.NewPage()
	if err != nil {
		log.Fatalf("Failed to create page: %v", err)
	}

	// Add title
	err = page.AddText("GxPDF Text Rendering", 100, 750, creator.HelveticaBold, 24)
	if err != nil {
		log.Fatalf("Failed to add title: %v", err)
	}

	// Add subtitle
	err = page.AddText("Standard 14 Fonts Demo", 100, 720, creator.Helvetica, 16)
	if err != nil {
		log.Fatalf("Failed to add subtitle: %v", err)
	}

	// Demonstrate different fonts
	y := 680.0
	fonts := []struct {
		name creator.FontName
		text string
	}{
		{creator.Helvetica, "Helvetica (Sans-serif)"},
		{creator.HelveticaBold, "Helvetica-Bold"},
		{creator.HelveticaOblique, "Helvetica-Oblique"},
		{creator.TimesRoman, "Times-Roman (Serif)"},
		{creator.TimesBold, "Times-Bold"},
		{creator.TimesItalic, "Times-Italic"},
		{creator.Courier, "Courier (Monospace)"},
		{creator.CourierBold, "Courier-Bold"},
	}

	for _, f := range fonts {
		err = page.AddText(f.text, 100, y, f.name, 12)
		if err != nil {
			log.Fatalf("Failed to add text: %v", err)
		}
		y -= 20
	}

	// Demonstrate colors
	y -= 20
	err = page.AddText("Colored Text:", 100, y, creator.HelveticaBold, 14)
	if err != nil {
		log.Fatalf("Failed to add colored text header: %v", err)
	}
	y -= 25

	colors := []struct {
		color creator.Color
		name  string
	}{
		{creator.Red, "Red"},
		{creator.Green, "Green"},
		{creator.Blue, "Blue"},
		{creator.Black, "Black"},
		{creator.Gray, "Gray"},
	}

	for _, col := range colors {
		err = page.AddTextColor(col.name, 100, y, creator.Helvetica, 12, col.color)
		if err != nil {
			log.Fatalf("Failed to add colored text: %v", err)
		}
		y -= 20
	}

	// Add footer
	err = page.AddTextColor(
		"Generated by GxPDF - The best open-source PDF library for Go",
		100, 50, creator.HelveticaOblique, 10, creator.Gray,
	)
	if err != nil {
		log.Fatalf("Failed to add footer: %v", err)
	}

	// Write to file
	outputPath := "text_rendering_example.pdf"
	err = c.WriteToFile(outputPath)
	if err != nil {
		log.Fatalf("Failed to write PDF: %v", err)
	}

	fmt.Printf("PDF created successfully: %s\n", outputPath)
}
